version: '3'

services:
  api:
    hostname: api
    build: ./Backend
    networks:
      - appnet
    ports:
      - '5000:5000'

  client:
    build: ./Frontend
    networks:
      - appnet
    ports:
      - '3005:3000'

networks:
  appnet:
    driver: bridge
