version: '3'

services:
  api:
    build: ./Backend
    networks:
      - appnet

  client:
    build: ./Frontend
    ports:
      - '3000:3000'
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
