version: '3'

services:
  nginx:
    image: nginx:1.15
    networks:
      - appnet
    ports:
      - '80:80'
    volumes:
      - ./config/nuxtapp.conf:/etc/nginx/conf.d/default.conf
      - ./Frontend/dist:/var/www/html/nuxtapp

  server:
    build: ./Backend
    networks:
      - appnet

  client:
    build: ./Frontend
    ports:
      - '3000:3000'
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
